[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "thunderbird"                                                                           # For fetching event tile data
terminal = "kitty"                                                                                        # Used to start applications

[debug]
try_suppress_errors = false  # Disables the error screen for errors
try_suppress_warnings = false # Disables the error screen for warnings

[appearance]
width = 700 # Sets the width of the main window
height = 500 # Sets the height of the main window
gsk_renderer = "cairo" # Sets the rendering engine. [ngl, cairo, ]
recolor_icons = true # If set to true, uses the [icon-name]-symbolic icons
icon_paths = ["~/.local/share/icons/hicolor/128x128/apps/","/home/moonburst/.local/share/icons/Avalon-Icons/apps/48/" ] # Sets where the application should look for custom icons
icon_size = 32 # Sets the icon size for the tiles

[behavior]
caching = false                                 # If set to true, will enable caching
cache = "~/.cache/sherlock/sherlock_desktop_cache.json" # Sets the location for caching files
daemonize = false                              # Enables daemon mode
animate = false                               # Enables startup animations

[binds]
prev = "None" # Sets an additional bind for selection the previous item in the list
next = "None" # Sets an additional bind for selection the next item in the list
