

[default_apps]
teams = "teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --url {meeting_url}"
calendar_client = "thunderbird"
terminal = "kitty"
browser = "/usr/sbin/vivaldi-stable"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "usd"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
log_level = "debug"
app_paths = []

[appearance]
width = 700
height = 500
gsk_renderer = "cairo"
icon_paths = ["~/.local/share/icons/hicolor/128x128/apps/","/home/moonburst/.local/share/icons/Avalon-Icons/apps/48/" ]
icon_size = 32
use_base_css = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
use_xdg_data_dir_icons = true
animate = false
daemonize = true


[binds]
up = "control-k"
down = "control-j"
left = "control-h"
right = "control-l"
context = "control-i"
modifier = "control"
exec_inplace = "control-return"

[files]
config = "/home/moonburst/.config/sherlock/config.toml"
css = "/home/moonburst/.config/sherlock/main.css"
fallback = "/home/moonburst/.config/sherlock/fallback.json"
alias = "/home/moonburst/.config/sherlock/sherlock_alias.json"
ignore = "/home/moonburst/.config/sherlock/sherlockignore"
actions = "/home/moonburst/.config/sherlock/sherlock_actions.json"

[runtime]
multi = true
center = true
photo_mode = true
display_raw = true
daemonize = true

[caching]
enable = false
cache = "/home/moonburst/.cache/sherlock/desktop_cache.bin"

[expand]
enable = false
edge = "top"
margin = 0

[backdrop]
enable = false
opacity = 0.6
edge = "top"

[status_bar]
enable = false

[search_bar_icon]
enable = false
icon = "system-search-symbolic"
icon_back = "sherlock-back"
size = 32
