
# exec --no-startup-id bash -c "cd ~/Documents && node sendChat.js > /tmp/sendChat.log 2>&1 &"
# exec obs
# Define Environment Variables
env = 7900, MESA_VK_DEVICE_SELECT=1002:744c! DRI_PRIME=pci-0000:28:00.0
env = 6400, MESA_VK_DEVICE_SELECT=1002:743f! DRI_PRIME=pci-0000:2b:00.0
exec-once = vivaldi
exec-once = vesktop
exec-once = steam -nochatui -silent
exec-once = nicotine
# exec syncthing
# exec dunst
exec-once = corectrl
# Background Services
exec-once = swayidle
exec-once = ~/.config/waybar/waybar.sh
exec-once = wl-paste --type text --watch cliphist store -max-items 50
exec-once = wl-paste --type image --watch cliphist store -max-items 10
exec-once = hyprland-autoname-workspaces

# Application with GPU Requirement (Applying $6400)
# OBS: Apply $6400 for encoding performance
exec-once= env $6400 obs
# exec MESA_VK_DEVICE_SELECT=1002:744c DRI_PRIME=pci-0000:28:00.0 vkcube
exec-once= env MESA_VK_DEVICE_SELECT=1002:743f DRI_PRIME=pci-0000:2b:00.0 steam -nochatui -silent

