### Monitor Configuration: All Flipped 180 Degrees (transform, 2) ###

# AOC 24G2W1G4 0x0000E8FA (Left Monitor - Primary)
# Flipped 180 degrees
monitor=desc:AOC 24G2W1G4 0x0000E8FA, 1920x1080@144, 0x0, 1, transform, 2

# HGC CR270HDM 0x00000001 (Center Monitor)
# Flipped 180 degrees
monitor=desc:HGC CR270HDM 0x00000001, 2560x1440@165, 1920x0, 1, transform, 2

# LG Electronics LG ULTRAWIDE 0x0003CBC2 (Right Monitor)
# Flipped 180 degrees
monitor=desc:LG Electronics LG ULTRAWIDE 0x0003CBC2, 2560x1080@60, 4480x0, 1, transform, 2


workspace = 1, monitor:desc:AOC 24G2W1G4 0x0000E8FA
workspace = 2, monitor:desc:HGC CR270HDM 0x00000001
workspace = 3, monitor:desc:LG Electronics LG ULTRAWIDE 0x0003CBC2
workspace = 4, monitor:desc:AOC 24G2W1G4 0x0000E8FA
workspace = 5, monitor:desc:HGC CR270HDM 0x00000001
workspace = 6, monitor:desc:LG Electronics LG ULTRAWIDE 0x0003CBC2
workspace = 7, monitor:desc:AOC 24G2W1G4 0x0000E8FA
workspace = 8, monitor:desc:HGC CR270HDM 0x00000001
workspace = 9, monitor:desc:LG Electronics LG ULTRAWIDE 0x0003CBC2
# This setting is defined in the bind section in Hyprland
# The default behavior is 'yes' (toggle), so this is how you turn it off:
bind = $SUPER, tab, workspace, last

