# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀▄░█░█░█░░░█▀▀░█▀▀
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀▄░█░█░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

#
# ░█▀▀░█░░░█▀█░█▀█░▀█▀░▀█▀░█▀█░█▀▀
# ░█▀▀░█░░░█░█░█▀█░░█░░░█░░█░█░█░█
# ░▀░░░▀▀▀░▀▀▀░▀░▀░░▀░░▀▀▀░▀░▀░▀▀▀
#
# 1. GROUPING RULE (HIGHEST PRIORITY)
windowrulev2 = group:set, class:^(.*)$
windowrulev2 = grouphint, class:^(.*)$ # (Recommended to go with group:set)


windowrulev2 = float, title:^(satty)$
windowrulev2 = size 800 800, class:^(.*satty.*)$
windowrulev2 = group:set, class:^(.*)$
windowrulev2 = grouphint, class:^(.*)$

#
# ░█▀█░█▀█░█▀█░█▀▀░▀█▀░▀█▀░█░█
# ░█░█░█▀▀░█▀█░█░░░░█░░░█░░░█░
# ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░░▀░░░▀░
#

#
# ░▀█▀░█▀▄░█░░░█▀▀░▀█▀░█▀█░█░█░▀█▀░█▀▄░▀█▀░▀█▀
# ░░█░░█░█░█░░░█▀▀░░█░░█░█░█▀█░░█░░█▀▄░░█░░░█░
# ░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀▀░░▀▀▀░░▀░
#
windowrulev2 = idleinhibit focus, class:^(hyperbeam).*
#windowrulev2 = idleinhibit focus, class:^(steam_app).*
windowrulev2 = idleinhibit focus, class:^(gamescope).*
windowrulev2 = idleinhibit focus, class:.*(cemu|yuzu|ryujinx|emulationstation|retroarch).*
windowrulev2 = idleinhibit fullscreen, title:.*(cemu|yuzu|ryujinx|emulationstation|retroarch).*
windowrulev2 = idleinhibit fullscreen, title:^(.*(Twitch|TNTdrama|YouTube|Bally Sports|Video Entertainment|Plex)).*(Firefox).*$
windowrulev2 = idleinhibit focus, title:^(.*(Twitch|TNTdrama|YouTube|Bally Sports|Video Entertainment|Plex)).*(Firefox).*$
#windowrulev2 = idleinhibit focus, class:^(mpv|.+exe)$
windowrulev2 = idleinhibit open, app_id:^(gamescope)$, title:^(Overwatch)$


#
# ░█░█░█▀█░█▀▄░█░█░█▀▀░█▀█░█▀█░█▀▀░█▀▀░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀
# ░█▄█░█░█░█▀▄░█▀▄░▀▀█░█▀▀░█▀█░█░░░█▀▀░░░█░░░█░█░█░█░█▀▀░░█░░█░█
# ░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀
#

windowrulev2 = workspace 1, title:^(.*(Twitch|TNTdrama|YouTube|Bally Sports|Video Entertainment|Plex)).*(Firefox).*$ # TODO: Doesnt seem to work even though it says it matches
windowrulev2 = workspace 1 silent, class:^(discord)$
windowrulev2 = workspace 1 silent, class:^(vesktop)$
windowrulev2 = workspace 1 silent, class:^(edopro)$
windowrulev2 = fullscreen, title:^(.edopro)$

#
# ░█▀█░▀█▀░█░█░█▀▀░█▀▄░░░█▀▄░█░█░█░░░█▀▀░█▀▀
# ░█░█░░█░░█▀█░█▀▀░█▀▄░░░█▀▄░█░█░█░░░█▀▀░▀▀█
# ░▀▀▀░░▀░░▀░▀░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀
#
windowrule = group, title:^(*)$
windowrulev2 = noborder, class:^steam_app.*$


